### ISSUE TITLE
*** FATAL LUA ERROR: [string "string"]:1: attempt to index global 'beamprofiler' (a nil value)

### ISSUE THREAD

**Issue by FanelliMarco** [vulcan-dev/beamprofiler#1]
Hello,
maybe i'm dumb but i can't reset the port and address from the beamng console following your instructions. When I enter 'beamprofiler.set_port(4444)' and 'beamprofiler.set_address(“127.0.0.1”)' I get an error (attached screenshot). I tried all the options in the drop-down menu. Anyway, cool small project with potential.
![Error_lua](https://github.com/user-attachments/assets/891912fc-a5f8-4018-93d0-88a3cc7b4a38)

**Comment by daniel-w0** [comment]
Hello, maybe try `extensions.beamprofiler`? If that doesn't work, then the extension/mod didn't load correctly. It should do the trick though :)

**Comment by FanelliMarco** [comment]
Hey there! Turns out I had a classic 'ID-10-T' error on my hands. 😅 I completely forgot to actually put the mod in the mods folder. Got it sorted now and everything's working.
